-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.config
(
    "orgId" uuid NOT NULL,
    config json DEFAULT '{}'::json,
    CONSTRAINT config_pkey PRIMARY KEY ("orgId")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.config
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.config TO anon;

GRANT ALL ON TABLE public.config TO postgres;

GRANT ALL ON TABLE public.config TO supabase_admin;

GRANT ALL ON TABLE public.config TO authenticated;

GRANT ALL ON TABLE public.config TO service_role;

DROP FUNCTION IF EXISTS graphql.build_delete(ast jsonb, variable_definitions jsonb, variables jsonb, parent_type text, parent_block_name text);

DROP FUNCTION IF EXISTS graphql.build_update(ast jsonb, variable_definitions jsonb, variables jsonb, parent_type text, parent_block_name text);

DROP FUNCTION IF EXISTS graphql.cache_key(role regrole, ast jsonb, variables jsonb);

DROP FUNCTION IF EXISTS graphql.build_insert(ast jsonb, variable_definitions jsonb, variables jsonb, parent_type text);
